# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 149eb6a19e28a2fb61af8826b1bb36140b5966f890a2c18e3e1e85b3c8d0b66f825b3ad78e121b033a602f811dd6d743d1685b3f6d7d1cbdfef4e4f54c2a6698

test:
  secret_key_base: a6969cf88f9eaeb55dd1ef0ab77767d294c08107c5a1a40d5cf6ebcd878ccfaec7a19a1dfdf1842ad1bf8b6d6d4749d87085f36d078dce7579b5a10199060121

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
